### ISSUE TITLE
transcription: text-align: justify

### ISSUE THREAD

**Issue by BOberreither** [karl-kraus/wpn-static#8]
Please add justified text alignment (Blocksatz) for the following renditions:
runningText1
runningText2
longQuote
longQuoteStart
longQuoteEnd
longQuoteIndent
longQuoteStartIndent
longQuoteMiddleIndent
longQuoteEndIndent
longQuoteMarginStart
longQuoteMarginMiddle
longQuoteMarginEnd

**Comment by linxOD** [comment]
Current rules for text alignment:

```CSS
#textcontent-pb .runningText1,
#textcontent-pb .runningText2,
#textcontent-pb .longQuote,
#textcontent-pb .typescriptLongQuoteLeading,
#textcontent-pb .longQuoteStart,
#textcontent-pb .longQuoteEnd,
#textcontent-pb .longQuoteStartIndent,
#textcontent-pb .longQuoteMarginStart,
#textcontent-pb .longQulongQuoteMiddleIndentoteEnd,
#textcontent-pb .longQuoteMarginMiddle,
#textcontent-pb .longQuoteEndIndent,
#textcontent-pb .longQuoteMarginEnd,
#textcontent-pb .longQuoteIndent {
  text-align: justify;
  text-align-last: justify;
}

#textcontent-pb .typescriptRunningText1,
#textcontent-pb .typescriptLongQuote,
#textcontent-pb .inkLongQuote,
#textcontent-pb .typescriptLongQuoteEnd,
#textcontent-pb .FackelQuote_columnRight {
  text-align: left;
  text-align-last: left;
}

#textcontent-pb .longQuoteVerse,
#textcontent-pb .inkLongQuoteVerse,
#textcontent-pb .typescriptLongQuoteVerse,
#textcontent-pb .typescriptLongQuoteVerseLeading,
#textcontent-pb .longQuoteVerseStart,
#textcontent-pb .longQuoteVerseStart {
  text-align-last: left;
  text-align: left;
  text-indent: 30px;
}

```
